// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:1056625974316:web:3d62cfd5a0b9a3be9b4589',
    messagingSenderId: '1056625974316',
    projectId: 'link-up-data-987c1',
    authDomain: 'link-up-data-987c1.firebaseapp.com',
    storageBucket: 'link-up-data-987c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0QY2KiMnUcwrAPz4rbTfciGdYP_Mmktc',
    appId: '1:1056625974316:android:2dbe0c568b77523e9b4589',
    messagingSenderId: '1056625974316',
    projectId: 'link-up-data-987c1',
    storageBucket: 'link-up-data-987c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkm_bANRCHY0EDEZpHO_PUY1WLDPu5T-Q',
    appId: '1:1056625974316:ios:dccff7a121ddbedd9b4589',
    messagingSenderId: '1056625974316',
    projectId: 'link-up-data-987c1',
    storageBucket: 'link-up-data-987c1.firebasestorage.app',
    androidClientId: '1056625974316-qa33evirkarvvfd33ummfepmija82l84.apps.googleusercontent.com',
    iosClientId: '1056625974316-niinjdlisthmsj9men5g9e1d6mqp65qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkUp',
  );

}